#!/usr/bin/env python3

# SPDX-FileCopyrightText: 2020 Pier Luigi Fiorini <pierluigi.fiorini@liri.io>
#
# SPDX-License-Identifier: MIT

import glob
import os
import subprocess
import tempfile


def main():
    tx_token = os.environ.get('INPUT_TX_TOKEN') or os.environ.get('TX_TOKEN')
    ssh_key = os.environ['INPUT_SSH_KEY']
    translations_folder = os.environ['INPUT_TRANSLATIONS_FOLDER']
    committer_email = os.environ.get('INPUT_COMMITTER_EMAIL', 'git-action@transifex.com')
    committer_name = os.environ.get('INPUT_COMMITTER_NAME', 'Transifex Github action')
    pull_translations = os.environ['INPUT_PULL_TRANSLATIONS'] == 'true'
    push_sources = os.environ['INPUT_PUSH_SOURCES'] == 'true'
    try:
        minimum_perc = int(os.environ.get('INPUT_MINIMUM_PERC', '0'))
    except ValueError:
        minimum_perc = 0

    args = []
    if minimum_perc > 0:
        args.append(f'--minimum-perc={minimum_perc}')

    # Save ssh key
    ssh_tempfile = ''
    if ssh_key:
        fd, ssh_tempfile = tempfile.mkstemp()
        with open(ssh_tempfile, 'w') as f:
            f.write(ssh_key)

    # Configure email and name
    subprocess.check_output(['git', 'config', '--local', 'user.email', committer_email])
    subprocess.check_output(['git', 'config', '--local', 'user.name', committer_name])

    # Default push policy
    subprocess.check_output(['git', 'config', 'push.default', 'simple'])

    # Git checkout action does a shallow clone. That prevents us to
    # access common history of branches
    subprocess.check_output(['git', 'fetch', '--unshallow'])

    # Discard changes
    subprocess.check_output(['git', 'stash'])

    # Push and pull
    if pull_translations:
        pull_args = ['tx', 'pull', '--no-interactive', '--force', '--all']
        subprocess.check_output(pull_args + args)
    if push_sources:
        subprocess.check_output(['tx', 'push', '--no-interactive', '--source'])

    # Add files
    paths = glob.glob(translations_folder, recursive=True)
    for path in paths:
        subprocess.check_output(['git', 'add', path])

    # Commit
    os.environ['GIT_SSH_COMMAND'] = f'ssh -i {ssh_tempfile} -o StrictHostKeyChecking=no'
    msg = 'Automatic merge of Transifex translations\n\n[ci skip]'
    subprocess.check_output(['git', 'commit', '--message=' + msg])
    subprocess.check_output(['git', 'push'])


if __name__ == '__main__':
    main()
